// Generated by CoffeeScript 1.9.0
(function() {
  var hello, squre, sum;

  hello = function() {
    return console.log("Hello, world.");
  };

  squre = function(x) {
    return x * x;
  };

  sum = function(x, y) {
    return x + y;
  };

  hello();

}).call(this);
